### ISSUE TITLE
Command name (options.id) is undefined in a hook

### ISSUE THREAD

**Issue by Zeko369** [oclif/config#108]
We had a problem in [this hook](https://github.com/blitz-js/blitz/blob/761daecd491838d539572dd2cee9b359e03f458e/packages/cli/src/checkBeforeRunning.ts#L9) which is the same as the [example](https://oclif.io/docs/hooks), where options.id was undefined.

```ts
console.log(options.id); // returns undefined
console.log((options as any).Command.id); // returns command name
```

At first I thought that it could be a problem because I ran it on the init hook, but the official example is pretty much this.

Did I use it wrong?, Are the TS annotations wrong?

**Comment by RasPhilCo** [comment]
Are you running an init hook? It's set as `id` [here](https://github.com/oclif/command/blob/136e7d4f35c7ac1087e6af920dcadf21bc73530f/src/main.ts#L13).

**Comment by Zeko369** [comment]
I think that at some point we switched to `prerun` hook by accident when testing something and forgot 😅, got it working now
