### ISSUE TITLE
(node:83072) SyntaxError Plugin: stocli: Unexpected token import

### ISSUE THREAD

**Issue by Junkern** [oclif/config#30]
When running oclif, I get the following error:

```
(node:83072) SyntaxError Plugin: stocli: Unexpected token import
module: @oclif/config@1.6.4
task: toCached
plugin: stocli
```
I have the latest versions installed.

**Comment by jdxcode** [comment]
You can't use import syntax without typescript

**Comment by Junkern** [comment]
I have no `.js` files in my `./src` folder (verified with `find ./src -iname "*.js"`)

Is there a way to enable debug logs, so I can take a look into that?

**Comment by jdxcode** [comment]
yes if you set `DEBUG=*`

**Comment by Junkern** [comment]
Okay, thank you! I was using a library which had a `.ts` file and import syntax.
