### ISSUE TITLE
We seem to be getting an error when the cli attempt to update plugins.

### ISSUE THREAD

**Issue by tnoonan-salesforce** [oclif/config#66]
We seem to be getting a new error in the cli that seems to be related to this change:

https://github.com/oclif/config/commit/e0b5e950b6700e23df6de91496e33703c75cb7e1

We are seeing cases in the sfdx-cli when parent.children is undefined and this 
results in the following error:

Installing dependencies for /Volumes/CaseAware/force-com-toolbelt... ⢿
(node:70974) TypeError Plugin: cli-engine: Cannot read property 'push' of undefined
module: @oclif/config@1.10.3
task: loadPlugins
plugin: cli-engine
root: /Users/tnoonan/tmp/node_modules/cli-engine
See more details with DEBUG=*
(node:70974) TypeError Plugin: cli-engine: Cannot read property 'push' of undefined
module: @oclif/config@1.10.3
task: loadPlugins
plugin: cli-engine
root: /Users/tnoonan/tmp/node_modules/cli-engine

Steps:

1) Completely remove sfdx from the system:

sudo rm -rf /usr/local/sfdx
sudo rm -rf /usr/local/lib/sfdx
sudo rm -rf /usr/local/bin/sfdx
sudo rm -rf ~/.local/share/sfdx ~/.config/sfdx ~/.cache/sfdx
sudo rm -rf ~/Library/Caches/sfdx

2) Install sfdx

npm install sfdx-cli

3) Install a plugin
node_modules/sfdx-cli/bin/run plugins:install salesforcedx@pre-release

This results in the error above.

**Comment by tnoonan-salesforce** [comment]
This seems to fix the issue for us.

https://github.com/oclif/config/pull/67

**Comment by tnoonan-salesforce** [comment]
@jdxcode @RasPhilCo Can one of you guys take a look a this?

**Comment by RasPhilCo** [comment]
closed via #68
