### ISSUE TITLE
question: why are all commands loaded up front?

### ISSUE THREAD

**Issue by Aghassi** [oclif/config#74]
https://github.com/oclif/config/blob/e0b5e950b6700e23df6de91496e33703c75cb7e1/src/plugin.ts#L170

I can see that for my companies CLI, we are requiring all 13 commands up front. Does this make sense/is it necessary? The CLI has the command I want when I pass in a command. What is the need for requiring all the other commands if I'm not going to use them? In our case, this is adding almost 3s to initial startup time.

**Comment by jdxcode** [comment]
it only does this in development mode, not when you release the CLI. Please use [spectrum](https://spectrum.chat/oclif) for this sort of discussion.

**Comment by Aghassi** [comment]
Will do, thanks @jdxcode . Wasn't aware from what I could find. I will message via spectrum in the future :).
