### ISSUE TITLE
Spurious warning for missing "files" in package.json

### ISSUE THREAD

**Issue by connec** [oclif/config#76]
https://github.com/oclif/config/blob/aedf35ee44def1b5502b55f036b6828315cad63c/src/plugin.ts#L109

There may be a good reason for this warning but it appears to me to be spurious, or at least in the wrong place, given that:

- There is a [documented default value](https://docs.npmjs.com/files/package.json#files) (`["*"]`).
- Omitting it shows the warning, but nothing breaks when using a command.

I can see this [was done intentionally](https://github.com/oclif/config/commit/cc73cb5) but there's no extra context I can find to explain why.

**Comment by jdxcode** [comment]
Removing it is a [bad practice](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d)

**Comment by connec** [comment]
That makes a lot of sense, thanks for the reference! I'm not sure it should be `oclif`'s job to 'lint' `package.json`s like that, but given all the included tooling for publishing and distributing CLIs I do get it.

I'll close this issue as I understand now, but do you think it would be worth either/both of:

- Moving the warning to packaging-related commands (e.g. part of `@oclif/dev-cli`)?
- Putting more info in the warning? This might also help raise awareness of the issue.

**Comment by Americas** [comment]
This is a very annoying warning, in private projects that are not published to npm there is no need for this property.
