### ISSUE TITLE
@oclif/parser should be a production dependency

### ISSUE THREAD

**Issue by elliottsj** [oclif/config#82]
Similar to https://github.com/oclif/command/issues/59

Right now, I need to specify `@oclif/parser` as a dependency of my CLI project, otherwise I encounter this error:

```
../../common/temp/node_modules/.registry.npmjs.org/@oclif/config/1.13.0/node_modules/@oclif/config/lib/command.d.ts:1:25 - error TS2307: Cannot find module '@oclif/parser'.

1 import * as Parser from '@oclif/parser';
                          ~~~~~~~~~~~~~~~
```

Since the typedef of `@oclif/config` depends on `@oclif/parser`, it should really be a production dependency.

**Comment by RasPhilCo** [comment]
Fixed https://github.com/oclif/config/commit/33b7bee70cd59a191ba40b52d079fd321ff27b95
