### ISSUE TITLE
@oclif/errors should be a dependency

### ISSUE THREAD

**Issue by aparajita** [oclif/config#83]
See [this line](https://github.com/oclif/config/blob/4b48574eebee25f10beaceea240ba5987dd5f8ab/src/config.ts#L1):

```js
import {CLIError, error, exit, warn} from '@oclif/errors'
```

`@oclif/errors` **must** be declared as a dependency, not a devDependency. The only reason you aren't getting bitten by this (mostly) is because the current implementation of `npm` and `yarn` are shamelessly flattening the package hierarchy, thus hiding missing dependency declarations.

**Comment by HosseinAgha** [comment]
I encountered this error when using apollo and [yarn pnp](https://next.yarnpkg.com/features/pnp). This is indeed a very huge. The problem is that you are relying on none standard behaviour.

**Comment by arcanis** [comment]
Related: https://github.com/oclif/oclif/issues/150
